context:
  version: "3.9.2"

package:
  name: rapidocr
  version: ${{ version }}

source:
  url: https://github.com/RapidAI/RapidOCR/archive/v${{ version }}.tar.gz
  sha256: 0342bb616322661038eec54e6d14935a09e13fd0bcfecc7d8c3faf16e34fa805

build:
  noarch: python
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
    content: cd python && python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=77
    - setuptools-scm >=8
  run:
    - python >=${{ python_min }}
    - pyclipper >=1.2.0
    - py-opencv >=4.5.1.48
    - numpy >=1.19.5,<3.0.0
    - six >=1.15.0
    - shapely >=1.7.1,!=2.0.4
    - pyyaml
    - pillow
    - tqdm
    - omegaconf !=2.2.1
    - requests
    - colorlog

tests:
  - python:
      imports:
        - rapidocr
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/RapidAI/RapidOCR
  summary: Awesome OCR Library
  description: |
    A cross platform OCR Library based on OnnxRuntime/OpenVINO/PaddlePaddle.
    It supports text detection and recognition.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://rapidai.github.io/RapidOCRDocs
  repository: https://github.com/RapidAI/RapidOCR

extra:
  recipe-maintainers:
    - kklein
